### ISSUE TITLE
Operator does not apply the passed images

### ISSUE THREAD

**Issue by sjmittal** [sky-big/pulsar-operator#13]
Here is the spec of the custom resource of the operator which was applied:
```
spec:
  bookie:
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.5.0
    storageClassName: standard
    journalStorageCapacity: 1
    ledgersStorageCapacity: 1
    size: 1
  broker:
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.5.0
    size: 1
  proxy:
    image:
      repository: apachepulsar/pulsar
      tag: 2.5.0
    size: 1
  zookeeper:
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.5.0
    size: 1
  manager:
    image:
      repository: apachepulsar/pulsar-manager
      tag: v0.1.0
    enable: true
```
However it looks like operator is still download latest images.
These are the tags I see in my local image registry:
```
apachepulsar/pulsar-all                   latest                         fa038de6df8d        5 days ago          3.03GB
apachepulsar/pulsar                       latest                         85891140d39a        5 days ago          1.77GB
apachepulsar/pulsar-manager               v0.1.0                         1aa52698573b        4 weeks ago         470MB
skybig/pulsar-operator                    latest                         6a5c0b11b2fe        3 months ago        47.1MB
apachepulsar/pulsar-all                   2.5.0                          77d849fb13b7        5 months ago        2.76GB
apachepulsar/pulsar                       2.5.0                          895e190fb267        5 months ago        1.52GB
```
Looks like it as downloaded both the latest images and images for the supplied tag. So somewhere in operator looks like latest tag is getting hardcoded or we may have some missing `image` attributes in the CR definition.

**Comment by sjmittal** [comment]
On further investigation it seems that for bookie autorecovery deployment it is still installing the latest image rather than one from supplied tag as I see:
`datastream-bookie-autorecovery-deployment-67b9cd9688-cqpkr   0/1     CrashLoopBackOff`

Also when I check the spec of the deployed instance I see that for zookeeper too it may have installed the latest image instead of one from supplied tag:

```
  Zookeeper:
    Image:
      Pull Policy:  Always
      Repository:   apachepulsar/pulsar-all
      Tag:          latest
    Pod:
      Components:
    Size:  1
```
Maybe these can be looked into.

**Comment by sky-big** [comment]
Can you see what the image field is in the Pod resource？

**Comment by sjmittal** [comment]
Here are the images current cluster is using:

deployments:
```
datastream-bookie-autorecovery-deployment   0/1     1            0           33h   replication-worker   apachepulsar/pulsar:latest           
datastream-broker-deployment                1/1     1            1           33h   broker               apachepulsar/pulsar-all:2.5.0        
datastream-manager-deployment               1/1     1            1           33h   manager              apachepulsar/pulsar-manager:v0.1.0   
datastream-proxy-deployment                 1/1     1            1           33h   proxy                apachepulsar/pulsar:2.5.0	  
```

statefulset:
```
datastream-bookie-statefulset      1/1     33h    bookie                              apachepulsar/pulsar-all:2.5.0
datastream-zookeeper-statefulset   1/1     33h    zookeeper                           apachepulsar/pulsar-all:latest
```
Looks like for `bookie-autorecovery` and `zookeeper` it is using the latest rather than supplied ones.

**Comment by sky-big** [comment]
I tested that the image of the ZooKeeper component can be set normally.
```
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  2m22s  default-scheduler  Successfully assigned kube-system/test-zookeeper-statefulset-0 to 10.0.0.4
  Normal  Pulling    2m21s  kubelet, 10.0.0.4  Pulling image "apachepulsar/pulsar-all:2.5.0"
```

**Comment by sky-big** [comment]
`bookie-autorecovery` It's hardcode. Let me fix it

**Comment by sky-big** [comment]
@sjmittal Currently, the image tags of all pulsar components are configurable, but there are problems with the official image of version 2.6.0. Currently, it is recommended to use 2.5.0. I have also tested it in this version and it works normally, as shown in the following configuration.
```
apiVersion: pulsar.apache.org/v1alpha1
kind: PulsarCluster
metadata:
  name: example-pulsarcluster
spec:
  autoRecovery:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.5.0
      pullPolicy: Always
  bookie:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.5.0
      pullPolicy: Always
  broker:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.5.0
      pullPolicy: Always
  proxy:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.5.0
      pullPolicy: Always
  zookeeper:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.5.0
      pullPolicy: Always
  monitor:
    enable: true
    prometheus:
      nodePort: 30006
    grafana:
      nodePort: 30007
```
