### ISSUE TITLE
pulsar-cluster pod is failing to start

### ISSUE THREAD

**Issue by shaloba** [sky-big/pulsar-operator#20]
I'm using the Pulsar operator for the first time and after it installation i configured the following cluster:

Cloud Platform EKS
K8s version 1.17

```

apiVersion: pulsar.apache.org/v1alpha1
kind: PulsarCluster
metadata:
  name: pulsar-cluster
spec:
  zookeeper:
    size: 3
  autoRecovery:
    size: 3
  bookie:
    size: 3
  broker:
    size: 3
  proxy:
    size: 3

  manager:
    enable: true
    host: pulsar.<my host>
    annotations:
      kubernetes.io/ingress.class: "nginx-cluster-internal"

  monitor:
    enable: true
    prometheusPort: 30002
    grafanaPort: 30003
    ingress:
      enable: true
      annotations:
        kubernetes.io/ingress.class: "nginx-cluster-internal"
```

After i run the kubectl apply command i encountered with the following error from the **pulsar-cluster-zookeeper-statefulset-0** pod

```
Traceback (most recent call last):
  File "bin/apply-config-from-env.py", line 50, in <module>
    k,v = line.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

Am i missing something in my installation / cluster config ?

**Comment by johanra** [comment]
@shaloba I have encountered the same issue which seems to be a [bug](https://github.com/apache/pulsar/issues/8704) in the latest pulsar docker image (2.7.0), apparently it is fixed in 2.7.1 but this hasn't been released yet.
As a workaround I downgraded the pulsar image to 2.6.3

```
apiVersion: pulsar.apache.org/v1alpha1
kind: PulsarCluster
metadata:
  name: pulsar
spec:
  autoRecovery:
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.6.3
      pullPolicy: IfNotPresent
  bookie:
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.6.3
      pullPolicy: IfNotPresent
    size: 3
  broker:
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.6.3
      pullPolicy: IfNotPresent
    size: 3
  proxy:
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.6.3
      pullPolicy: IfNotPresent
    size: 3
  zookeeper:
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.6.3
      pullPolicy: IfNotPresent
```

**Comment by sky-big** [comment]
Currently, it can only support the old version of 2.5.0. The image of the new version of Pulsar has been updated. We will follow up the adaptation later。
```
apiVersion: pulsar.apache.org/v1alpha1
kind: PulsarCluster
metadata:
  name: example-pulsarcluster
spec:
  autoRecovery:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.5.0
      pullPolicy: Always
  bookie:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.5.0
      pullPolicy: Always
  broker:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.5.0
      pullPolicy: Always
  proxy:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.5.0
      pullPolicy: Always
  zookeeper:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.5.0
      pullPolicy: Always
  monitor:
    enable: true
    prometheus:
      nodePort: 30006
    grafana:
      nodePort: 30007
```
@johanra  @shaloba
