### ISSUE TITLE
Bookkeeper and autorecovery won't start using Pulsar 2.5.0

### ISSUE THREAD

**Issue by rfuerst87** [sky-big/pulsar-operator#7]
Seems like Pulsar replaced the environment variable `PULSAR_MEM` by `BOOKIE_MEM`. Using `PULSAR_MEM` in Pulsar 2.5.0 causes an error in the startup process of Bookkeeper and Bookkeeper-Autorecovery which leads to a failed cluster state. See https://github.com/apache/pulsar/issues/6355 for more details.

**Comment by robshep** [comment]
Hi,
Hopefully it's OK to comment on this old&closed issue but using pulsar-operator/master as of 2020-07-21 these symptoms are occurring.

Maybe it's a regression or a new issue with the exact same symptom of failure, I can't be sure.

I don't know which image version is being pulled as the container metadata just mentions`pulsar-all:latest` is there a way to pin the version?

This is show for the statefulset pods and the autorecovery pods

```[conf/bookkeeper.conf] Applying config dbStorage_readAheadCacheMaxSizeMb = 32
[conf/bookkeeper.conf] Applying config dbStorage_writeCacheMaxSizeMb = 32
[conf/bookkeeper.conf] Applying config statsProviderClass = org.apache.bookkeeper.stats.prometheus.PrometheusMetricsProvider
[conf/bookkeeper.conf] Applying config zkServers = pulsar-prod-zookeeper-service
Error: Could not find or load main class "
```

**Comment by sky-big** [comment]
> Hi,
> Hopefully it's OK to comment on this old&closed issue but using pulsar-operator/master as of 2020-07-21 these symptoms are occurring.
> 
> Maybe it's a regression or a new issue with the exact same symptom of failure, I can't be sure.
> 
> I don't know which image version is being pulled as the container metadata just mentions`pulsar-all:latest` is there a way to pin the version?
> 
> This is show for the statefulset pods and the autorecovery pods
> 
> ```
> [conf/bookkeeper.conf] Applying config dbStorage_writeCacheMaxSizeMb = 32
> [conf/bookkeeper.conf] Applying config statsProviderClass = org.apache.bookkeeper.stats.prometheus.PrometheusMetricsProvider
> [conf/bookkeeper.conf] Applying config zkServers = pulsar-prod-zookeeper-service
> Error: Could not find or load main class "
> ```

**Comment by sky-big** [comment]
> Hi,
> Hopefully it's OK to comment on this old&closed issue but using pulsar-operator/master as of 2020-07-21 these symptoms are occurring.
> 
> Maybe it's a regression or a new issue with the exact same symptom of failure, I can't be sure.
> 
> I don't know which image version is being pulled as the container metadata just mentions`pulsar-all:latest` is there a way to pin the version?
> 
> This is show for the statefulset pods and the autorecovery pods
> 
> ```
> [conf/bookkeeper.conf] Applying config dbStorage_writeCacheMaxSizeMb = 32
> [conf/bookkeeper.conf] Applying config statsProviderClass = org.apache.bookkeeper.stats.prometheus.PrometheusMetricsProvider
> [conf/bookkeeper.conf] Applying config zkServers = pulsar-prod-zookeeper-service
> Error: Could not find or load main class "
> ```

@wolfstudy Please take a look at the problem.

**Comment by wolfstudy** [comment]
Thanks @robshep feedback. The issue has been fixed.

> I don't know which image version is being pulled as the container metadata just mentions `pulsar-all:latest` is there a way to pin the version?

`pulsar-all:latest` means the latest version of pulsar, currently the version is 2.6.0. reference to: https://hub.docker.com/repository/docker/apachepulsar/pulsar-all

**Comment by robshep** [comment]
Thanks @wolfstudy 

Fixed when/where?   This happens now with master/HEAD

**Comment by wolfstudy** [comment]
> Fixed when/where?

In pulsar 2.6.0, reference to https://github.com/apache/pulsar/pull/6373

> This happens now with master/HEAD

Maybe you can try to use [pulsar-all:2.6.0](https://hub.docker.com/layers/apachepulsar/pulsar-all/2.6.0/images/sha256-d93e9ac275fe0a6f71d0fd4c9e68d2efb64d4c6fa165c1c07e6c0928d7762fa5?context=repo)?

In the helm chart, we use this [version](https://github.com/apache/pulsar-helm-chart/blob/master/charts/pulsar/values.yaml#L135)

**Comment by robshep** [comment]
Thanks @wolfstudy 

> is there a way to pin the version?  

How can I force a specific version that the operator will use?  

Thanks

**Comment by wolfstudy** [comment]
> How can I force a specific version that the operator will use?

Maybe @sky-big will have a good way

**Comment by sky-big** [comment]
```
spec:
  bookie:
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.6.0
    storageClassName: standard
    journalStorageCapacity: 1
    ledgersStorageCapacity: 1
    size: 1
  broker:
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.6.0
    size: 1
  proxy:
    image:
      repository: apachepulsar/pulsar
      tag: 2.6.0
    size: 1
  zookeeper:
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.6.0
    size: 1
  manager:
    image:
      repository: apachepulsar/pulsar-manager
      tag: v0.1.0
    enable: true
```
@robshep Refer to the CR resources for configuring PulsarCluster in this way.

**Comment by robshep** [comment]
@sky-big thanks for the assistance, 

Same symptom for bookie, I'm afraid

> bookie Error: Could not find or load main class "

**Comment by sky-big** [comment]
> @sky-big thanks for the assistance,
> 
> Same symptom for bookie, I'm afraid
> 
> > bookie Error: Could not find or load main class "

Is the Pod image V2.6.0? Please check it.

**Comment by robshep** [comment]
My CRD is as you have it configured above:

```apiVersion: pulsar.apache.org/v1alpha1
kind: PulsarCluster
metadata:
  name: pulsar-staging
spec:
  bookie:
    size: 1
    storageClassName: "do-block-storage"                
    journalStorageCapacity: 5              
    ledgersStorageCapacity: 5             
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.6.0
  broker:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.6.0
  proxy:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.6.0
  zookeeper:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.6.0
  monitor:
    enable: true                
    prometheusPort: 30002      
    grafanaPort: 30003        
    ingress:                 
      enable: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
  manager:
    enable: true            
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.6.0
    host: pulsar-manager.pethau.io
    annotations:
      kubernetes.io/ingress.class: "nginx"
```

**Comment by sky-big** [comment]
Please check what is the corresponding image in the Pod of BookKeeper and AutoRecovery.

**Comment by robshep** [comment]
Hi,

Please excuse the JPG info, it's the easiest way for me to capture this.

Here is pulsar-staging-bookie-statefulset-0

You can see the init container is using `apachepulsar/pulsar:latest `
But the main container is using `apachepulsar/pulsar-all:2.6.0`
The shasum of each is different. 

![image](https://user-images.githubusercontent.com/1799763/88167280-7d2f0d00-cc10-11ea-8674-9680f0527559.png)

And here is pulsar-staging-bookie-autorecovery-deployment-[...]

This is using `apachepulsar/pulsar:latest` 

![image](https://user-images.githubusercontent.com/1799763/88167559-ee6ec000-cc10-11ea-9e6f-4aa4deb5d7f3.png)

**Comment by sky-big** [comment]
```
kind: PulsarCluster
metadata:
  name: pulsar-staging
spec:
  bookie:
    size: 1
    storageClassName: "do-block-storage"                
    journalStorageCapacity: 5              
    ledgersStorageCapacity: 5             
    image:
      repository: apachepulsar/pulsar-all
      tag: latest
      pullPolicy: Always
  broker:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: latest
      pullPolicy: Always
  proxy:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: latest
      pullPolicy: Always
  zookeeper:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: latest
      pullPolicy: Always
  monitor:
    enable: true                
    prometheusPort: 30002      
    grafanaPort: 30003        
    ingress:                 
      enable: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
  manager:
    enable: true            
    image:
      repository: apachepulsar/pulsar-all
      tag: latest
      pullPolicy: Always
    host: pulsar-manager.pethau.io
    annotations:
      kubernetes.io/ingress.class: "nginx"
```
@robshep Please use it in this way first. There are some problems at present, which need to be optimized later.

**Comment by robshep** [comment]
THanks @sky-big 

Same issue, sadly. 

CR as you've described it above using `pullPolicy: Always`. 

I can confirm using `:latest` for all units and I've matched the SHA sums for `pulsar:latest` and `pulsar-all:latest` match the checksums for 2.6.0 release.

Thank you for diagnosing this far.

Rob

**Comment by robshep** [comment]
Did you mean to close this? 

> Same issue, sadly.

Still not working.

**Comment by sky-big** [comment]
@wolfstudy The Image has been upgraded to V2.6.0, but the user said that the error still exists. Please help to have a look again.

**Comment by sky-big** [comment]
@robshep  I'll fix the problem by Operator, please wait a moment.

**Comment by sky-big** [comment]
@robshep Currently, the image tags of all pulsar components are configurable, but there are problems with the official image of version 2.6.0. Currently, it is recommended to use 2.5.0. I have also tested it in this version and it works normally, as shown in the following configuration.
```
apiVersion: pulsar.apache.org/v1alpha1
kind: PulsarCluster
metadata:
  name: example-pulsarcluster
spec:
  autoRecovery:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.5.0
      pullPolicy: Always
  bookie:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.5.0
      pullPolicy: Always
  broker:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.5.0
      pullPolicy: Always
  proxy:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.5.0
      pullPolicy: Always
  zookeeper:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.5.0
      pullPolicy: Always
  monitor:
    enable: true
    prometheus:
      nodePort: 30006
    grafana:
      nodePort: 30007
```
